# Generated by Django 3.2 on 2022-04-09 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adderess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catonment_board', models.BooleanField()),
                ('house_number', models.CharField(max_length=50)),
                ('ward_number', models.CharField(max_length=50)),
                ('city_union', models.CharField(max_length=50)),
                ('district_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_day', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('lorn_orphan', models.BooleanField(blank=True, null=True)),
                ('birth_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_place', to='myapp.adderess')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_name', to='myapp.parent')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_name', to='myapp.parent')),
                ('permanent_adderess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_adderess', to='myapp.adderess')),
                ('present_adderess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present_adderess', to='myapp.adderess')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
